/** ивенты сцены */
export const GAME_EVENTS = {
    START_GAME: "START_GAME",
    GAME_OVER: "GAME_OVER",
    PAUSE: "PAUSE",
    RESUME: "RESUME",
    RESTART: "RESTART",
    CURRENT_SCENE_READY: "CURRENT_SCENE_READY",
    OPEN_MENU: "OPEN_MENU",
    OPEN_MAIN: "OPEN_MAIN",
    DINO_JUMP: "DINO_JUMP",
    DINO_STOP_JUMP: "DINO_STOP_JUMP",
    DINO_BEND_DOWN: "DINO_BEND_DOWN",
    DINO_STOP_BEND_DOWN: "DINO_STOP_BEND_DOWN",
};

/** карта глубины */
export const DEPTH_MAP = {
    DINO: 10,
    MODAL: 20,
};
